#!/bin/sh
'''exec' /home/conda/feedstock_root/build_artifacts/bld/rattler-build_idna_1779999227/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python "$0" "$@"
' '''
import sys
from idna.cli import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
