"""Fixed-capacity GPU replay for recovery transitions generated by the policy."""

from __future__ import annotations

import torch


class AmpReplayBuffer:
    def __init__(self, capacity: int, state_dim: int, device: str | torch.device):
        if capacity <= 0 or state_dim <= 0:
            raise ValueError(f"capacity and state_dim must be positive, got {capacity}, {state_dim}")
        self.capacity = capacity
        self.device = torch.device(device)
        self.states = torch.empty(capacity, state_dim, device=self.device)
        self.next_states = torch.empty_like(self.states)
        self.cursor = 0
        self.size = 0

    def insert(self, states: torch.Tensor, next_states: torch.Tensor) -> None:
        if states.shape != next_states.shape or states.ndim != 2 or states.shape[1] != self.states.shape[1]:
            raise ValueError(
                f"Invalid replay transition shapes: states={tuple(states.shape)}, "
                f"next_states={tuple(next_states.shape)}"
            )
        count = states.shape[0]
        if count == 0:
            return
        states = states.detach()
        next_states = next_states.detach()
        if count >= self.capacity:
            self.states.copy_(states[-self.capacity :])
            self.next_states.copy_(next_states[-self.capacity :])
            self.cursor = 0
            self.size = self.capacity
            return

        first_count = min(count, self.capacity - self.cursor)
        self.states[self.cursor : self.cursor + first_count].copy_(states[:first_count])
        self.next_states[self.cursor : self.cursor + first_count].copy_(next_states[:first_count])
        remaining = count - first_count
        if remaining:
            self.states[:remaining].copy_(states[first_count:])
            self.next_states[:remaining].copy_(next_states[first_count:])
        self.cursor = (self.cursor + count) % self.capacity
        self.size = min(self.capacity, self.size + count)

    def sample(self, batch_size: int) -> tuple[torch.Tensor, torch.Tensor]:
        if self.size == 0:
            raise RuntimeError("Cannot sample an empty AMP replay buffer.")
        indices = torch.randint(self.size, (batch_size,), device=self.device)
        return self.states[indices], self.next_states[indices]

    def __len__(self) -> int:
        return self.size
